name: stronzflix
description: "Streaming application."
publish_to: 'none'

version: 0.2.7

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
      sdk: flutter
  async: ^2.11.0
  background_downloader: ^8.5.3
  cast: ^2.1.0
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  ffmpeg_kit_flutter: ^6.0.3
  flutter_hls_parser: ^2.0.1
  flutter_svg: ^2.0.10+1
  html: ^0.15.4
  html_unescape: ^2.0.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  peerdart: ^0.5.4
  pointycastle: ^3.9.1
  process_run: ^0.14.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  win32_registry: ^1.1.4
  wakelock_plus: ^1.2.8
  stronz_video_player:
    git: https://github.com/StronzLabs/StronzVideoPlayer.git
  sutils:
    git: https://github.com/StronzLabs/SUtils.git
  js_unpack: ^1.0.4
  auto_size_text: ^3.0.0
  castscreen:
    git: https://github.com/Bonfra04/dart_castscreen.git

dependency_overrides:
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
